[project]
name="eca-pytest-030"
version="2024.03.16"
dependencies=[
    "numpy~=1.26.4",
    "pandas~=2.2.2",
    "pytest~=8.3.4",
    "pytest-json-report",
    "pytest-xdist",
    "requests~=2.32.3",
    "tabulate~=0.9.0"]
